import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '@/styles/globals.css';
import '@/styles/app.scss';
import React from "react";
import PrivateLayout from "@/components/layouts/PrivateLayout";

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Sample NextJs Contact App',
  description: 'Generated by Landbridge',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
    <body>
    <PrivateLayout  children={children}/>
    </body>
    </html>
  );
}
